title: Intelligent Systems and Operations in Aviation 
description: This site introduces the research group which is part of the Institute for Data Analysis 
and Process Design at the ZHAW and is led by Dr. Manuel Renold.
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
