title: Tipsy
description: Discover Tipsy: Track your drinks, see what friends are trying, earn badges, and explore statistics. Cheers to your next great find!
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
