title: Yentl | Race Up
description: Run batch tests on humans for Formula Student entry tests.

# url
url: "raceup.github.io"  # the base hostname & protocol for your site
baseurl: "/yentl"  # the subpath of your site, e.g. /blog/

google_analytics:
theme: jekyll-theme-cayman
github:
  repository_name: yentl
  repository_url: https://github.com/raceup/yentl
  owner_name: raceup
  owner_url: https://github.com/raceup
